"""
Sphinx configuration for haive.

This configuration uses PyDevelop-Docs shared configuration.
Generated by pydevelop-docs init.
"""

import os
import sys
from datetime import date

# -- Path setup --------------------------------------------------------------
sys.path.insert(0, os.path.abspath("../.."))

# -- Project information -----------------------------------------------------
project = "haive"
copyright = f"{date.today().year}, haive Team"
author = "haive Team"
release = "0.1.0"

# -- Import centralized Haive configuration ----------------------------------
from haive_docs_config import get_haive_config

# Get the standardized configuration for the main hub
_config = get_haive_config(
    package_name="haive",
    source_path="../../scripts"  # Main hub doesn't need package source
)

# Remove AutoAPI extension and config for main hub
if 'extensions' in _config:
    _config['extensions'] = [ext for ext in _config['extensions'] if ext != 'autoapi.extension']

# Remove AutoAPI-related keys
autoapi_keys = [k for k in _config.keys() if k.startswith('autoapi_')]
for key in autoapi_keys:
    del _config[key]

# Apply all configuration settings
for key, value in _config.items():
    if key not in ['project', 'copyright', 'author', 'release']:
        globals()[key] = value

# -- Project-specific overrides ----------------------------------------------
# Disable AutoAPI for main hub (just focus on navigation)
autoapi_dirs = []

# -- Additional setup --------------------------------------------------------

def setup(app):
    """Add custom setup for navigation dropdown."""
    app.add_js_file('navigation-dropdown.js')
    """Sphinx setup hook."""
    # Modern CSS files (matches html_css_files)
    css_files = [
        "enhanced-design.css",
        "breadcrumb-navigation.css", 
        "mermaid-custom.css",
        "tippy-enhancements.css"
    ]
    for css_file in css_files:
        if os.path.exists("_static/" + css_file):
            app.add_css_file(css_file)
    
    # Legacy fallback
    if os.path.exists("_static/css/custom.css"):
        app.add_css_file("css/custom.css")
        
    if os.path.exists("_static/js/api-enhancements.js"):
        app.add_js_file("js/api-enhancements.js")
