"""Central hub Sphinx configuration for monorepo documentation.

Generated by
pydevelop-docs with AutoAPI hierarchical organization.

✅ INCLUDES AUTOAPI HIERARCHICAL FIX - Issue #4 Solution
This central hub configuration coordinates individual package documentation
that each use hierarchical AutoAPI organization instead of flat listings.
"""

from __future__ import annotations

from pydevelop_docs.config import get_haive_config

# Get central hub configuration with hierarchical support
config = get_haive_config(
    package_name="Haive Documentation",
    package_path=".",
    is_central_hub=True,
)

# Collections configuration - aggregates hierarchically organized package docs
collections = {
    "packages": {
        "driver": "copy_folder",
        "source": "../packages/*/docs/build/html",
        "target": "packages",
    },
}

# ✅ Central hub benefits from individual packages using autoapi_own_page_level="module"
globals().update(config)
