#!/bin/bash
# Safe auto-fix script for Haive
# Generated by safe_autofix_analyzer.py

set -e # Exit on error

echo "Safe Auto-fix Script for Haive"
echo "=============================="
echo
echo "This script will apply SAFE auto-fixes that won't break the codebase."
echo "All changes can be reviewed with git diff before committing."
echo

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Function to run command with output
run_fix() {
	local cmd="$1"
	local desc="$2"

	echo -e "${YELLOW}Running: $desc${NC}"
	echo "Command: $cmd"

	if [ "$DRY_RUN" = "true" ]; then
		echo -e "${GREEN}[DRY RUN] Would execute: $cmd${NC}"
		# Add --dry-run or equivalent flag
		if [[ $cmd == *"ruff"* ]]; then
			$cmd --diff
		elif [[ $cmd == *"trunk"* ]]; then
			$cmd --dry-run
		fi
	else
		$cmd
	fi

	echo
}

# Check for dry run
DRY_RUN=false
if [ "$1" = "--dry-run" ] || [ "$1" = "-n" ]; then
	DRY_RUN=true
	echo -e "${YELLOW}DRY RUN MODE - No changes will be made${NC}"
	echo
fi

# Ensure we're in the right directory
cd "$(dirname "$0")/../.."

# Step 1: Format with ruff (safe)
run_fix "poetry run ruff format ." "Formatting code with ruff"

# Step 2: Fix imports (safe)
run_fix "poetry run ruff check --fix --select I,F401" "Fixing imports (sorting and removing unused)"

# Step 3: Fix trailing whitespace (safe)
run_fix "poetry run ruff check --fix --select W291,W292,W293" "Removing trailing whitespace"

# Step 4: Fix blank lines (safe)
run_fix "poetry run ruff check --fix --select E301,E302,E303,E304,E305" "Fixing blank line issues"

# Step 5: Remove unnecessary type: ignore (safe)
run_fix "poetry run ruff check --fix --select PGH003" "Removing unnecessary type: ignore comments"

# Step 6: Update type annotations (safe)
run_fix "poetry run ruff check --fix --select UP035,UP006" "Updating type annotation syntax"

# Step 7: Fix quote consistency (safe)
run_fix "poetry run ruff check --fix --select Q" "Standardizing quotes"

# Step 8: Trunk format (if available)
if command -v trunk &>/dev/null; then
	run_fix "trunk fmt" "Running trunk format"
fi

echo -e "${GREEN}Auto-fix complete!${NC}"
echo
echo "Review changes with:"
echo "  git diff"
echo
echo "If everything looks good, commit with:"
echo "  git add -A"
echo "  git commit -m 'chore: apply safe auto-fixes (imports, formatting, whitespace)'"
