#!/usr/bin/env python3
"""
Haive Package Documentation Sync Script
Distributes shared documentation configuration to all packages
"""

import os
import shutil
from pathlib import Path
from typing import Dict, List

# Package configuration mapping
PACKAGES = {
    "haive-core": {
        "title": "Haive Core Framework",
        "description": "Core components, engines, and base infrastructure for the Haive AI Agent Framework",
        "color": "#2563eb",  # Blue
    },
    "haive-agents": {
        "title": "Haive Agents",
        "description": "Pre-built AI agents with specialized capabilities and workflows",
        "color": "#059669",  # Green
    },
    "haive-dataflow": {
        "title": "Haive Dataflow",
        "description": "Data processing pipelines and persistence systems for Haive agents",
        "color": "#7c3aed",  # Purple
    },
    "haive-games": {
        "title": "Haive Games",
        "description": "Game-playing agents and tournament systems for competitive AI",
        "color": "#dc2626",  # Red
    },
    "haive-mcp": {
        "title": "Haive MCP",
        "description": "Model Context Protocol integration and server management",
        "color": "#ea580c",  # Orange
    },
    "haive-tools": {
        "title": "Haive Tools",
        "description": "Utility tools and helper functions for AI agent development",
        "color": "#0891b2",  # Cyan
    },
    "haive-prebuilt": {
        "title": "Haive Prebuilt",
        "description": "Ready-to-use components and templates for rapid agent development",
        "color": "#be123c",  # Rose
    },
}


class DocsSync:
    def __init__(self, repo_root: Path):
        self.repo_root = repo_root
        self.shared_docs = repo_root / "shared" / "docs"
        self.packages_dir = repo_root / "packages"
        self.template_file = self.shared_docs / "conf_template_full.py"

    def sync_all_packages(self):
        """Sync documentation to all packages"""
        print("🚀 Starting Haive Package Documentation Sync")
        print(f"📁 Repository root: {self.repo_root}")
        print(f"📦 Packages directory: {self.packages_dir}")
        print(f"📋 Template file: {self.template_file}")
        print()

        # Verify template exists
        if not self.template_file.exists():
            raise FileNotFoundError(f"Template file not found: {self.template_file}")

        # Read template content
        template_content = self.template_file.read_text()

        # Process each package
        for package_name, config in PACKAGES.items():
            print(f"📦 Processing {package_name}...")
            self.sync_package(package_name, config, template_content)
            print(f"✅ {package_name} documentation synced")
            print()

        print("🎉 All packages synchronized successfully!")

    def sync_package(self, package_name: str, config: Dict, template_content: str):
        """Sync documentation for a single package"""
        package_dir = self.packages_dir / package_name
        docs_dir = package_dir / "docs"
        source_dir = docs_dir / "source"

        # Create docs directory structure
        docs_dir.mkdir(exist_ok=True)
        source_dir.mkdir(exist_ok=True)
        (source_dir / "_static").mkdir(exist_ok=True)
        (source_dir / "_templates").mkdir(exist_ok=True)
        (source_dir / "_autoapi_templates").mkdir(exist_ok=True)

        # Copy shared static assets
        self.copy_shared_assets(source_dir)

        # Generate customized conf.py
        customized_conf = self.customize_template(
            template_content, package_name, config
        )
        (source_dir / "conf.py").write_text(customized_conf)

        # Generate package-specific index.rst
        index_content = self.generate_index_rst(package_name, config)
        (source_dir / "index.rst").write_text(index_content)

        # Copy/create Makefile
        makefile_content = self.generate_makefile()
        (docs_dir / "Makefile").write_text(makefile_content)
        (docs_dir / "make.bat").write_text(self.generate_make_bat())

    def customize_template(self, template: str, package_name: str, config: Dict) -> str:
        """Customize template for specific package"""
        # Template substitutions
        customized = template.replace(
            "# Generated Sphinx Configuration\\n# Auto-generated by PyAutoDoc ConfigLoader\\n# DO NOT EDIT MANUALLY - Edit YAML files instead",
            f'# {config["title"]} - Sphinx Documentation Configuration\\n# Generated from Haive shared documentation template\\n# Customized for {package_name}',
        )

        # Path setup - PyAutoDoc used ../../src, packages use ../src
        customized = customized.replace(
            'sys.path.insert(0, os.path.abspath("../../src"))',
            'sys.path.insert(0, os.path.abspath("../src"))',
        )

        # Project information
        customized = customized.replace(
            'project = "pyautodoc"', f'project = "{config["title"]}"'
        )
        customized = customized.replace(
            'author = "William R. Astley"', 'author = "Haive Team"'
        )
        customized = customized.replace(
            'copyright = "2025, William R. Astley"', 'copyright = "2025, Haive Team"'
        )

        # AutoAPI configuration - PyAutoDoc used ["../../src"], packages use ["../src"]
        customized = customized.replace(
            'autoapi_dirs = ["../../src"]', 'autoapi_dirs = ["../src"]'
        )

        # Update repository references
        customized = customized.replace(
            '"source_repository": "https://github.com/yourusername/pyautodoc/"',
            '"source_repository": "https://github.com/prim8/haive/"',
        )
        customized = customized.replace(
            '"source_directory": "docs/"',
            f'"source_directory": "packages/{package_name}/docs/"',
        )

        # Update branding
        customized = customized.replace(
            'html_baseurl = "https://pyautodoc.readthedocs.io/"',
            f'html_baseurl = "https://haive.readthedocs.io/packages/{package_name}/"',
        )

        # Update OpenGraph metadata
        customized = customized.replace(
            'ogp_site_url = "https://pyautodoc.readthedocs.io/"',
            f'ogp_site_url = "https://haive.readthedocs.io/packages/{package_name}/"',
        )
        customized = customized.replace(
            'ogp_site_name = "PyAutoDoc"', f'ogp_site_name = "{config["title"]}"'
        )
        customized = customized.replace(
            'ogp_site_description = "Hyper-organized documentation system with intense Furo theming"',
            f'ogp_site_description = "{config["description"]}"',
        )

        # Update announcement
        customized = customized.replace(
            '"announcement": "🚀 <strong>PyAutoDoc 0.1.0</strong> - Hyper-organized documentation with intense Furo theming!"',
            f'"announcement": "🚀 <strong>{config["title"]}</strong> - {config["description"]}"',
        )

        # Update GitHub URLs in footer
        customized = customized.replace(
            '"url": "https://github.com/yourusername/pyautodoc/"',
            '"url": "https://github.com/prim8/haive/"',
        )

        # Update GitHub issues
        customized = customized.replace(
            'issues_github_path = "yourusername/pyautodoc"',
            'issues_github_path = "prim8/haive"',
        )
        customized = customized.replace(
            'issues_uri = "https://github.com/yourusername/pyautodoc/issues/{issue}"',
            'issues_uri = "https://github.com/prim8/haive/issues/{issue}"',
        )

        # Update color scheme with package-specific colors
        primary_color = config["color"]
        customized = customized.replace(
            '"color-brand-primary": "#2563eb"',  # Default blue
            f'"color-brand-primary": "{primary_color}"',
        )

        # Update git tracking paths
        customized = customized.replace(
            'sphinx_git_tracked_files = ["docs/source/"]',
            f'sphinx_git_tracked_files = ["packages/{package_name}/docs/"]',
        )

        # Update setup print message
        customized = customized.replace(
            'print("✨ Intense Furo theme with sphinx-design enabled!")',
            f'print("✨ {config["title"]} documentation loaded successfully!")',
        )

        return customized

    def generate_index_rst(self, package_name: str, config: Dict) -> str:
        """Generate package-specific index.rst"""
        package_part = package_name.replace("haive-", "")

        return f"""
{config["title"]} Documentation
{'=' * (len(config["title"]) + 13)}

Welcome to **{config["title"]}** - {config["description"]}.

This package is part of the Haive AI Agent Framework, providing specialized functionality for AI agent development and deployment.

.. note::
   {config["title"]} integrates seamlessly with other Haive packages. See the :doc:`complete framework documentation <../../docs/index>` for the full ecosystem.

Features
--------

* 🚀 **Production Ready**: Battle-tested components for real-world AI applications
* 🔧 **Developer Friendly**: Comprehensive API documentation and examples  
* ⚡ **High Performance**: Optimized for speed and efficiency
* 🔌 **Extensible**: Easy to customize and extend for specific needs

Quick Start
-----------

.. code-block:: python

   from haive.{package_part} import *
   
   # Package-specific quick start example will be added here
   # Check the examples section for detailed usage patterns

.. toctree::
   :maxdepth: 2
   :caption: Documentation
   
   autoapi/index
   
.. toctree::
   :maxdepth: 1
   :caption: Links
   
   GitHub Repository <https://github.com/prim8/haive>
   Haive Framework Documentation <../../docs/index>

Indices and Tables
==================

* :ref:`genindex`
* :ref:`modindex`  
* :ref:`search`
""".strip()

    def generate_makefile(self) -> str:
        """Generate standard Sphinx Makefile"""
        return """# Minimal makefile for Sphinx documentation
#

# You can set these variables from the command line, and also
# from the environment for the first two.
SPHINXOPTS    ?=
SPHINXBUILD   ?= sphinx-build
SOURCEDIR     = source
BUILDDIR      = build

# Put it first so that "make" without argument is like "make help".
help:
	@$(SPHINXBUILD) -M help "$(SOURCEDIR)" "$(BUILDDIR)" $(SPHINXOPTS) $(O)

.PHONY: help Makefile

# Catch-all target: route all unknown targets to Sphinx using the new
# "make mode" option.  $(O) is meant as a shortcut for $(SPHINXOPTS).
%: Makefile
	@$(SPHINXBUILD) -M $@ "$(SOURCEDIR)" "$(BUILDDIR)" $(SPHINXOPTS) $(O)
"""

    def generate_make_bat(self) -> str:
        """Generate Windows batch file for Sphinx"""
        return """@ECHO OFF

pushd %~dp0

REM Command file for Sphinx documentation

if "%SPHINXBUILD%" == "" (
	set SPHINXBUILD=sphinx-build
)
set SOURCEDIR=source
set BUILDDIR=build

%SPHINXBUILD% >NUL 2>NUL
if errorlevel 9009 (
	echo.
	echo.The 'sphinx-build' command was not found. Make sure you have Sphinx
	echo.installed, then set the SPHINXBUILD environment variable to point
	echo.to the full path of the 'sphinx-build' executable. Alternatively you
	echo.may add the Sphinx directory to PATH.
	echo.
	echo.If you don't have Sphinx installed, grab it from
	echo.https://www.sphinx-doc.org/
	exit /b 1
)

if "%1" == "" goto help

%SPHINXBUILD% -M %1 %SOURCEDIR% %BUILDDIR% %SPHINXOPTS% %O%
goto end

:help
%SPHINXBUILD% -M help %SOURCEDIR% %BUILDDIR% %SPHINXOPTS% %O%

:end
popd
"""

    def copy_shared_assets(self, target_source_dir: Path):
        """Copy shared static assets and templates from the main docs"""
        main_docs = self.repo_root / "docs" / "source"

        # Copy static files if they exist
        static_src = main_docs / "_static"
        static_dst = target_source_dir / "_static"
        if static_src.exists():
            # Copy key CSS/JS files
            key_files = [
                "furo-intense.css",
                "api-docs.css",
                "mermaid-custom.css",
                "toc-enhancements.css",
                "tippy-enhancements.css",
                "furo-enhancements.js",
                "mermaid-config.js",
                "toc-navigator.js",
            ]
            for file_name in key_files:
                src_file = static_src / file_name
                if src_file.exists():
                    shutil.copy2(src_file, static_dst / file_name)

        # Copy template files if they exist
        templates_src = main_docs / "_templates"
        templates_dst = target_source_dir / "_templates"
        if templates_src.exists():
            if templates_src.is_dir():
                shutil.copytree(templates_src, templates_dst, dirs_exist_ok=True)

        # Copy autoapi templates
        autoapi_src = main_docs / "_autoapi_templates"
        autoapi_dst = target_source_dir / "_autoapi_templates"
        if autoapi_src.exists():
            if autoapi_src.is_dir():
                shutil.copytree(autoapi_src, autoapi_dst, dirs_exist_ok=True)


def main():
    """Main entry point"""
    repo_root = Path(__file__).parent.parent.parent
    sync = DocsSync(repo_root)
    sync.sync_all_packages()


if __name__ == "__main__":
    main()
