#!/usr/bin/env python3
"""Comprehensive nitpick_ignore list expansion for Haive Sphinx documentation.

This provides a comprehensive set of commonly missing type references
that should be ignored in Sphinx nitpicky mode to reduce noise and focus
on actual issues.
"""

# COMPREHENSIVE NITPICK_IGNORE LIST FOR HAIVE
# Add these to your conf.py nitpick_ignore list

EXPANDED_NITPICK_IGNORE = [
    # =========================================================================
    # BASIC PYTHON TYPES
    # =========================================================================
    ("py:class", "str"),
    ("py:class", "int"),
    ("py:class", "bool"),
    ("py:class", "float"),
    ("py:class", "list"),
    ("py:class", "dict"),
    ("py:class", "tuple"),
    ("py:class", "set"),
    ("py:class", "frozenset"),
    ("py:class", "bytes"),
    ("py:class", "bytearray"),
    ("py:class", "None"),
    ("py:class", "type"),
    ("py:class", "object"),
    ("py:class", "slice"),
    ("py:class", "range"),
    ("py:class", "enumerate"),
    ("py:class", "zip"),
    ("py:class", "filter"),
    ("py:class", "map"),
    # =========================================================================
    # TYPING MODULE
    # =========================================================================
    ("py:class", "Any"),
    ("py:class", "List"),
    ("py:class", "Dict"),
    ("py:class", "Tuple"),
    ("py:class", "Set"),
    ("py:class", "FrozenSet"),
    ("py:class", "Optional"),
    ("py:class", "Union"),
    ("py:class", "Callable"),
    ("py:class", "Type"),
    ("py:class", "TypeVar"),
    ("py:class", "Generic"),
    ("py:class", "Literal"),
    ("py:class", "Protocol"),
    ("py:class", "TypedDict"),
    ("py:class", "ClassVar"),
    ("py:class", "Final"),
    ("py:class", "Annotated"),
    ("py:class", "Iterator"),
    ("py:class", "Iterable"),
    ("py:class", "Generator"),
    ("py:class", "AsyncIterator"),
    ("py:class", "AsyncIterable"),
    ("py:class", "AsyncGenerator"),
    ("py:class", "Awaitable"),
    ("py:class", "Coroutine"),
    ("py:class", "Sequence"),
    ("py:class", "MutableSequence"),
    ("py:class", "Mapping"),
    ("py:class", "MutableMapping"),
    ("py:class", "Collection"),
    ("py:class", "Container"),
    ("py:class", "Sized"),
    ("py:class", "Hashable"),
    ("py:class", "Reversible"),
    ("py:class", "SupportsInt"),
    ("py:class", "SupportsFloat"),
    ("py:class", "SupportsBytes"),
    ("py:class", "SupportsComplex"),
    ("py:class", "SupportsIndex"),
    ("py:class", "SupportsRound"),
    ("py:class", "IO"),
    ("py:class", "TextIO"),
    ("py:class", "BinaryIO"),
    # =========================================================================
    # TYPING_EXTENSIONS
    # =========================================================================
    ("py:class", "typing_extensions.Any"),
    ("py:class", "typing_extensions.Union"),
    ("py:class", "typing_extensions.Optional"),
    ("py:class", "typing_extensions.List"),
    ("py:class", "typing_extensions.Dict"),
    ("py:class", "typing_extensions.Tuple"),
    ("py:class", "typing_extensions.Set"),
    ("py:class", "typing_extensions.Literal"),
    ("py:class", "typing_extensions.Protocol"),
    ("py:class", "typing_extensions.TypedDict"),
    ("py:class", "typing_extensions.Final"),
    ("py:class", "typing_extensions.Annotated"),
    ("py:class", "typing_extensions.NotRequired"),
    ("py:class", "typing_extensions.Required"),
    ("py:class", "typing_extensions.Self"),
    ("py:class", "typing_extensions.TypeAlias"),
    ("py:class", "typing_extensions.ParamSpec"),
    ("py:class", "typing_extensions.TypeVarTuple"),
    ("py:class", "typing_extensions.Unpack"),
    # =========================================================================
    # DATETIME TYPES
    # =========================================================================
    ("py:class", "datetime.datetime"),
    ("py:class", "datetime.date"),
    ("py:class", "datetime.time"),
    ("py:class", "datetime.timedelta"),
    ("py:class", "datetime.timezone"),
    ("py:class", "datetime.tzinfo"),
    # =========================================================================
    # COLLECTIONS TYPES
    # =========================================================================
    ("py:class", "collections.abc.Mapping"),
    ("py:class", "collections.abc.MutableMapping"),
    ("py:class", "collections.abc.Sequence"),
    ("py:class", "collections.abc.MutableSequence"),
    ("py:class", "collections.abc.Set"),
    ("py:class", "collections.abc.MutableSet"),
    ("py:class", "collections.abc.Iterator"),
    ("py:class", "collections.abc.Iterable"),
    ("py:class", "collections.abc.Generator"),
    ("py:class", "collections.abc.AsyncIterator"),
    ("py:class", "collections.abc.AsyncIterable"),
    ("py:class", "collections.abc.AsyncGenerator"),
    ("py:class", "collections.abc.Awaitable"),
    ("py:class", "collections.abc.Coroutine"),
    ("py:class", "collections.abc.Callable"),
    ("py:class", "collections.OrderedDict"),
    ("py:class", "collections.defaultdict"),
    ("py:class", "collections.Counter"),
    ("py:class", "collections.deque"),
    ("py:class", "collections.ChainMap"),
    ("py:class", "collections.UserDict"),
    ("py:class", "collections.UserList"),
    ("py:class", "collections.UserString"),
    # =========================================================================
    # PATHLIB TYPES
    # =========================================================================
    ("py:class", "pathlib.Path"),
    ("py:class", "pathlib.PurePath"),
    ("py:class", "pathlib.PosixPath"),
    ("py:class", "pathlib.WindowsPath"),
    ("py:class", "pathlib.PurePosixPath"),
    ("py:class", "pathlib.PureWindowsPath"),
    # =========================================================================
    # ASYNCIO TYPES
    # =========================================================================
    ("py:class", "asyncio.Future"),
    ("py:class", "asyncio.Task"),
    ("py:class", "asyncio.Event"),
    ("py:class", "asyncio.Lock"),
    ("py:class", "asyncio.Semaphore"),
    ("py:class", "asyncio.BoundedSemaphore"),
    ("py:class", "asyncio.Condition"),
    ("py:class", "asyncio.Queue"),
    ("py:class", "asyncio.LifoQueue"),
    ("py:class", "asyncio.PriorityQueue"),
    ("py:class", "asyncio.AbstractEventLoop"),
    ("py:class", "asyncio.BaseEventLoop"),
    # =========================================================================
    # PYDANTIC TYPES
    # =========================================================================
    ("py:class", "BaseModel"),
    ("py:class", "pydantic.BaseModel"),
    ("py:class", "pydantic.v1.BaseModel"),
    ("py:class", "Field"),
    ("py:class", "pydantic.Field"),
    ("py:class", "pydantic.fields.Field"),
    ("py:class", "SecretStr"),
    ("py:class", "pydantic.SecretStr"),
    ("py:class", "SecretBytes"),
    ("py:class", "pydantic.SecretBytes"),
    ("py:class", "ConfigDict"),
    ("py:class", "pydantic.ConfigDict"),
    ("py:class", "pydantic.config.ConfigDict"),
    ("py:class", "ValidationError"),
    ("py:class", "pydantic.ValidationError"),
    ("py:class", "pydantic.error_wrappers.ValidationError"),
    ("py:class", "BaseSettings"),
    ("py:class", "pydantic.BaseSettings"),
    ("py:class", "pydantic_settings.BaseSettings"),
    ("py:class", "validator"),
    ("py:class", "pydantic.validator"),
    ("py:class", "field_validator"),
    ("py:class", "pydantic.field_validator"),
    ("py:class", "model_validator"),
    ("py:class", "pydantic.model_validator"),
    ("py:class", "root_validator"),
    ("py:class", "pydantic.root_validator"),
    ("py:class", "Json"),
    ("py:class", "pydantic.Json"),
    ("py:class", "EmailStr"),
    ("py:class", "pydantic.EmailStr"),
    ("py:class", "HttpUrl"),
    ("py:class", "pydantic.HttpUrl"),
    ("py:class", "AnyUrl"),
    ("py:class", "pydantic.AnyUrl"),
    ("py:class", "FilePath"),
    ("py:class", "pydantic.FilePath"),
    ("py:class", "DirectoryPath"),
    ("py:class", "pydantic.DirectoryPath"),
    ("py:class", "PositiveInt"),
    ("py:class", "pydantic.PositiveInt"),
    ("py:class", "NonNegativeInt"),
    ("py:class", "pydantic.NonNegativeInt"),
    ("py:class", "PositiveFloat"),
    ("py:class", "pydantic.PositiveFloat"),
    ("py:class", "NonNegativeFloat"),
    ("py:class", "pydantic.NonNegativeFloat"),
    ("py:class", "StrictStr"),
    ("py:class", "pydantic.StrictStr"),
    ("py:class", "StrictInt"),
    ("py:class", "pydantic.StrictInt"),
    ("py:class", "StrictFloat"),
    ("py:class", "pydantic.StrictFloat"),
    ("py:class", "StrictBool"),
    ("py:class", "pydantic.StrictBool"),
    ("py:class", "constr"),
    ("py:class", "pydantic.constr"),
    ("py:class", "conint"),
    ("py:class", "pydantic.conint"),
    ("py:class", "confloat"),
    ("py:class", "pydantic.confloat"),
    ("py:class", "UUID1"),
    ("py:class", "pydantic.UUID1"),
    ("py:class", "UUID3"),
    ("py:class", "pydantic.UUID3"),
    ("py:class", "UUID4"),
    ("py:class", "pydantic.UUID4"),
    ("py:class", "UUID5"),
    ("py:class", "pydantic.UUID5"),
    # =========================================================================
    # LANGCHAIN TYPES
    # =========================================================================
    ("py:class", "Document"),
    ("py:class", "langchain.schema.Document"),
    ("py:class", "langchain_core.documents.Document"),
    ("py:class", "BaseMessage"),
    ("py:class", "langchain.schema.BaseMessage"),
    ("py:class", "langchain_core.messages.BaseMessage"),
    ("py:class", "HumanMessage"),
    ("py:class", "langchain.schema.HumanMessage"),
    ("py:class", "langchain_core.messages.HumanMessage"),
    ("py:class", "AIMessage"),
    ("py:class", "langchain.schema.AIMessage"),
    ("py:class", "langchain_core.messages.AIMessage"),
    ("py:class", "SystemMessage"),
    ("py:class", "langchain.schema.SystemMessage"),
    ("py:class", "langchain_core.messages.SystemMessage"),
    ("py:class", "ToolMessage"),
    ("py:class", "langchain.schema.ToolMessage"),
    ("py:class", "langchain_core.messages.ToolMessage"),
    ("py:class", "FunctionMessage"),
    ("py:class", "langchain.schema.FunctionMessage"),
    ("py:class", "langchain_core.messages.FunctionMessage"),
    ("py:class", "ChatMessage"),
    ("py:class", "langchain.schema.ChatMessage"),
    ("py:class", "langchain_core.messages.ChatMessage"),
    ("py:class", "BaseTool"),
    ("py:class", "langchain.tools.BaseTool"),
    ("py:class", "langchain_core.tools.BaseTool"),
    ("py:class", "Tool"),
    ("py:class", "langchain.tools.Tool"),
    ("py:class", "langchain_core.tools.Tool"),
    ("py:class", "StructuredTool"),
    ("py:class", "langchain.tools.StructuredTool"),
    ("py:class", "langchain_core.tools.StructuredTool"),
    ("py:class", "BaseLanguageModel"),
    ("py:class", "langchain.base_language.BaseLanguageModel"),
    ("py:class", "langchain_core.language_models.BaseLanguageModel"),
    ("py:class", "BaseLLM"),
    ("py:class", "langchain.llms.base.BaseLLM"),
    ("py:class", "langchain_core.language_models.llms.BaseLLM"),
    ("py:class", "BaseChatModel"),
    ("py:class", "langchain.chat_models.base.BaseChatModel"),
    ("py:class", "langchain_core.language_models.chat_models.BaseChatModel"),
    ("py:class", "BaseRetriever"),
    ("py:class", "langchain.schema.retriever.BaseRetriever"),
    ("py:class", "langchain_core.retrievers.BaseRetriever"),
    ("py:class", "VectorStore"),
    ("py:class", "langchain.vectorstores.base.VectorStore"),
    ("py:class", "langchain_core.vectorstores.VectorStore"),
    ("py:class", "BaseEmbeddings"),
    ("py:class", "langchain.embeddings.base.BaseEmbeddings"),
    ("py:class", "langchain_core.embeddings.Embeddings"),
    ("py:class", "BaseMemory"),
    ("py:class", "langchain.memory.base.BaseMemory"),
    ("py:class", "langchain_core.memory.BaseMemory"),
    ("py:class", "BasePromptTemplate"),
    ("py:class", "langchain.prompts.base.BasePromptTemplate"),
    ("py:class", "langchain_core.prompts.BasePromptTemplate"),
    ("py:class", "PromptTemplate"),
    ("py:class", "langchain.prompts.PromptTemplate"),
    ("py:class", "langchain_core.prompts.PromptTemplate"),
    ("py:class", "ChatPromptTemplate"),
    ("py:class", "langchain.prompts.ChatPromptTemplate"),
    ("py:class", "langchain_core.prompts.ChatPromptTemplate"),
    ("py:class", "BaseOutputParser"),
    ("py:class", "langchain.schema.output_parser.BaseOutputParser"),
    ("py:class", "langchain_core.output_parsers.BaseOutputParser"),
    ("py:class", "OutputParserException"),
    ("py:class", "langchain.schema.output_parser.OutputParserException"),
    ("py:class", "langchain_core.exceptions.OutputParserException"),
    ("py:class", "BaseCallbackHandler"),
    ("py:class", "langchain.callbacks.base.BaseCallbackHandler"),
    ("py:class", "langchain_core.callbacks.BaseCallbackHandler"),
    ("py:class", "CallbackManager"),
    ("py:class", "langchain.callbacks.manager.CallbackManager"),
    ("py:class", "langchain_core.callbacks.manager.CallbackManager"),
    ("py:class", "Runnable"),
    ("py:class", "langchain.schema.runnable.Runnable"),
    ("py:class", "langchain_core.runnables.Runnable"),
    ("py:class", "RunnableConfig"),
    ("py:class", "langchain.schema.runnable.RunnableConfig"),
    ("py:class", "langchain_core.runnables.RunnableConfig"),
    ("py:class", "RunnablePassthrough"),
    ("py:class", "langchain.schema.runnable.RunnablePassthrough"),
    ("py:class", "langchain_core.runnables.RunnablePassthrough"),
    ("py:class", "RunnableLambda"),
    ("py:class", "langchain.schema.runnable.RunnableLambda"),
    ("py:class", "langchain_core.runnables.RunnableLambda"),
    ("py:class", "RunnableParallel"),
    ("py:class", "langchain.schema.runnable.RunnableParallel"),
    ("py:class", "langchain_core.runnables.RunnableParallel"),
    ("py:class", "RunnableSequence"),
    ("py:class", "langchain.schema.runnable.RunnableSequence"),
    ("py:class", "langchain_core.runnables.RunnableSequence"),
    # =========================================================================
    # LANGGRAPH TYPES
    # =========================================================================
    ("py:class", "StateGraph"),
    ("py:class", "langgraph.graph.StateGraph"),
    ("py:class", "MessageGraph"),
    ("py:class", "langgraph.graph.MessageGraph"),
    ("py:class", "CompiledGraph"),
    ("py:class", "langgraph.graph.CompiledGraph"),
    ("py:class", "Graph"),
    ("py:class", "langgraph.graph.Graph"),
    ("py:class", "GraphState"),
    ("py:class", "langgraph.graph.state.GraphState"),
    ("py:class", "BaseCheckpointSaver"),
    ("py:class", "langgraph.checkpoint.base.BaseCheckpointSaver"),
    ("py:class", "MemorySaver"),
    ("py:class", "langgraph.checkpoint.memory.MemorySaver"),
    ("py:class", "SqliteSaver"),
    ("py:class", "langgraph.checkpoint.sqlite.SqliteSaver"),
    ("py:class", "PostgresSaver"),
    ("py:class", "langgraph.checkpoint.postgres.PostgresSaver"),
    ("py:class", "START"),
    ("py:class", "langgraph.constants.START"),
    ("py:class", "END"),
    ("py:class", "langgraph.constants.END"),
    ("py:class", "Send"),
    ("py:class", "langgraph.constants.Send"),
    # =========================================================================
    # COMMON LIBRARIES
    # =========================================================================
    ("py:class", "numpy.ndarray"),
    ("py:class", "np.ndarray"),
    ("py:class", "pandas.DataFrame"),
    ("py:class", "pd.DataFrame"),
    ("py:class", "pandas.Series"),
    ("py:class", "pd.Series"),
    ("py:class", "requests.Response"),
    ("py:class", "httpx.Response"),
    ("py:class", "aiohttp.ClientResponse"),
    ("py:class", "fastapi.Request"),
    ("py:class", "fastapi.Response"),
    ("py:class", "uuid.UUID"),
    ("py:class", "decimal.Decimal"),
    ("py:class", "fractions.Fraction"),
    ("py:class", "enum.Enum"),
    ("py:class", "enum.IntEnum"),
    ("py:class", "enum.Flag"),
    ("py:class", "enum.IntFlag"),
    ("py:class", "logging.Logger"),
    ("py:class", "threading.Thread"),
    ("py:class", "threading.Lock"),
    ("py:class", "threading.RLock"),
    ("py:class", "threading.Event"),
    ("py:class", "threading.Semaphore"),
    ("py:class", "multiprocessing.Process"),
    ("py:class", "multiprocessing.Queue"),
    ("py:class", "concurrent.futures.Future"),
    ("py:class", "concurrent.futures.ThreadPoolExecutor"),
    ("py:class", "concurrent.futures.ProcessPoolExecutor"),
    # =========================================================================
    # GENERIC TYPE VARIABLES AND PLACEHOLDERS
    # =========================================================================
    ("py:class", "T"),
    ("py:class", "K"),
    ("py:class", "V"),
    ("py:class", "P"),
    ("py:class", "R"),
    ("py:class", "S"),
    ("py:class", "U"),
    ("py:class", "TIn"),
    ("py:class", "TOut"),
    ("py:class", "TState"),
    ("py:class", "TConfig"),
    ("py:class", "TResult"),
    ("py:class", "TData"),
    ("py:class", "TModel"),
    ("py:class", "TEngine"),
    ("py:class", "TAgent"),
    ("py:class", "TTool"),
    ("py:class", "TRetriever"),
    ("py:class", "TMemory"),
    ("py:class", "TCallback"),
    ("py:class", "TRunnable"),
    ("py:class", "TPrompt"),
    ("py:class", "TOutput"),
    ("py:class", "TInput"),
    ("py:class", "_T"),
    ("py:class", "_K"),
    ("py:class", "_V"),
    ("py:class", "_P"),
    ("py:class", "_R"),
    ("py:class", "~T"),
    ("py:class", "~K"),
    ("py:class", "~V"),
    ("py:class", "~P"),
    ("py:class", "~R"),
    # =========================================================================
    # HAIVE INTERNAL TYPES (COMMON ONES)
    # =========================================================================
    ("py:class", "Agent"),
    ("py:class", "BaseAgent"),
    ("py:class", "MultiAgent"),
    ("py:class", "ReactAgent"),
    ("py:class", "SimpleAgent"),
    ("py:class", "AnswerAgent"),
    ("py:class", "RAGAgent"),
    ("py:class", "PlannerAgent"),
    ("py:class", "ExecutorAgent"),
    ("py:class", "InvokableEngine"),
    ("py:class", "AugLLMConfig"),
    ("py:class", "StateSchema"),
    ("py:class", "MetaStateSchema"),
    ("py:class", "MessagesState"),
    ("py:class", "GraphState"),
    ("py:class", "AgentState"),
    ("py:class", "BaseGraph"),
    ("py:class", "StateGraph"),
    ("py:class", "CompiledGraph"),
    ("py:class", "RecompileMixin"),
    ("py:class", "RetrieverMixin"),
    ("py:class", "MemoryMixin"),
    ("py:class", "ToolMixin"),
    ("py:class", "BaseEngineConfig"),
    ("py:class", "VectorStoreConfig"),
    ("py:class", "EmbeddingConfig"),
    ("py:class", "HuggingFaceEmbeddingConfig"),
    ("py:class", "OpenAIEmbeddingConfig"),
    ("py:class", "BaseRetrieverConfig"),
    ("py:class", "ChromaVectorStore"),
    ("py:class", "FAISSVectorStore"),
    ("py:class", "PineconeVectorStore"),
    ("py:class", "BaseStore"),
    ("py:class", "MemoryStore"),
    ("py:class", "PostgresStore"),
    ("py:class", "SqliteStore"),
    ("py:class", "BaseCheckpointer"),
    ("py:class", "MemoryCheckpointer"),
    ("py:class", "PostgresCheckpointer"),
    ("py:class", "SqliteCheckpointer"),
    # =========================================================================
    # FUNCTION AND METHOD REFERENCES
    # =========================================================================
    ("py:func", "tool"),
    ("py:func", "langchain.tools.tool"),
    ("py:func", "langchain_core.tools.tool"),
    ("py:meth", "BaseModel.model_validate"),
    ("py:meth", "BaseModel.model_dump"),
    ("py:meth", "BaseModel.model_copy"),
    ("py:meth", "BaseModel.model_construct"),
    ("py:meth", "BaseModel.model_json_schema"),
    ("py:meth", "Agent.run"),
    ("py:meth", "Agent.arun"),
    ("py:meth", "Agent.invoke"),
    ("py:meth", "Agent.ainvoke"),
    ("py:meth", "Agent.stream"),
    ("py:meth", "Agent.astream"),
    ("py:meth", "Agent.batch"),
    ("py:meth", "Agent.abatch"),
    # =========================================================================
    # ATTRIBUTE REFERENCES
    # =========================================================================
    ("py:attr", "config"),
    ("py:attr", "metadata"),
    ("py:attr", "state"),
    ("py:attr", "tools"),
    ("py:attr", "memory"),
    ("py:attr", "callbacks"),
    ("py:attr", "verbose"),
    ("py:attr", "tags"),
    ("py:attr", "run_name"),
    ("py:attr", "run_id"),
    ("py:attr", "parent_run_id"),
    # =========================================================================
    # MODULE REFERENCES
    # =========================================================================
    ("py:mod", "typing"),
    ("py:mod", "typing_extensions"),
    ("py:mod", "pydantic"),
    ("py:mod", "langchain"),
    ("py:mod", "langchain_core"),
    ("py:mod", "langgraph"),
    ("py:mod", "asyncio"),
    ("py:mod", "collections"),
    ("py:mod", "collections.abc"),
    ("py:mod", "datetime"),
    ("py:mod", "pathlib"),
    ("py:mod", "uuid"),
    ("py:mod", "enum"),
    ("py:mod", "logging"),
    ("py:mod", "threading"),
    ("py:mod", "multiprocessing"),
    ("py:mod", "concurrent.futures"),
    # =========================================================================
    # DATA REFERENCES
    # =========================================================================
    ("py:data", "TYPE_CHECKING"),
    ("py:data", "typing.TYPE_CHECKING"),
    ("py:data", "MISSING"),
    ("py:data", "dataclasses.MISSING"),
    ("py:data", "NOTHING"),
    ("py:data", "attrs.NOTHING"),
    # =========================================================================
    # EXCEPTION REFERENCES
    # =========================================================================
    ("py:exc", "ValidationError"),
    ("py:exc", "pydantic.ValidationError"),
    ("py:exc", "TypeError"),
    ("py:exc", "ValueError"),
    ("py:exc", "AttributeError"),
    ("py:exc", "KeyError"),
    ("py:exc", "IndexError"),
    ("py:exc", "RuntimeError"),
    ("py:exc", "NotImplementedError"),
    ("py:exc", "FileNotFoundError"),
    ("py:exc", "PermissionError"),
    ("py:exc", "ImportError"),
    ("py:exc", "ModuleNotFoundError"),
    ("py:exc", "asyncio.TimeoutError"),
    ("py:exc", "concurrent.futures.TimeoutError"),
]


def format_for_conf_py():
    """Format the list for easy copy-paste into conf.py."""

    lines = ["# Comprehensive nitpick_ignore list - add to your conf.py"]
    lines.append("nitpick_ignore = [")

    current_section = ""
    for ref_type, target in EXPANDED_NITPICK_IGNORE:
        # Add section comments for readability
        if ref_type != current_section:
            lines.append(f"    # {ref_type.upper()} REFERENCES")
            current_section = ref_type

        lines.append(f'    ("{ref_type}", "{target}"),')

    lines.append("]")
    return "\n".join(lines)


def save_to_file():
    """Save the formatted list to a file."""
    from pathlib import Path

    content = format_for_conf_py()
    output_file = Path("expanded_nitpick_ignore_for_conf.py")
    output_file.write_text(content)

    print(f"Expanded nitpick_ignore list saved to: {output_file}")
    print(f"Total entries: {len(EXPANDED_NITPICK_IGNORE)}")

    # Show breakdown by type
    from collections import Counter

    type_counts = Counter(item[0] for item in EXPANDED_NITPICK_IGNORE)
    print("\nBreakdown by reference type:")
    for ref_type, count in type_counts.most_common():
        print(f"  {ref_type}: {count} entries")


if __name__ == "__main__":
    save_to_file()
