"""
Sphinx configuration for test-project.
Generated by pydevelop-docs.
"""

import os
import sys

# Path setup
sys.path.insert(0, os.path.abspath("../.."))

# Import pydevelop-docs configuration
try:
    from pydevelop_docs.config import get_haive_config
    config = get_haive_config(
        package_name="test-project",
        package_path="../..",
        is_central_hub=False
    )
    globals().update(config)
except ImportError:
    # Fallback to embedded configuration
    
    project = "test-project"
    extensions = ["sphinx.ext.autodoc", "sphinx.ext.napoleon"]
    html_theme = "furo"

