"""Modular Documentation Sessions.

This module provides nox sessions for building package-specific
documentation using the new modular configuration system.
"""

from pathlib import Path
import shutil
import tempfile
import time

import nox

# Project paths
PROJECT_ROOT = Path(__file__).parent.parent
DOCS_DIR = PROJECT_ROOT / "docs"
CONF_MODULES_DIR = DOCS_DIR / "source" / "conf_modules"

# Python versions to test
PYTHON_VERSIONS = ["3.12"]

# Base dependencies - only what's needed for the modular system
BASE_DEPENDENCIES = [
    "sphinx>=8.0.0",
    "furo",  # Default theme
    "myst-parser",  # Markdown support
    "sphinx-autoapi",  # API documentation
]

# Extended dependencies for standard/full profiles
EXTENDED_DEPENDENCIES = [
    # Essential extensions used by most packages
    "sphinx-design",
    "sphinx-copybutton",
    "sphinx-autodoc-typehints",
    "autodocsumm",
    "sphinxcontrib-autodoc-pydantic",
    # Common UI/UX Extensions
    "sphinx-tabs",
    "sphinx-togglebutton",
    "sphinx-inline-tabs",
    "sphinx-paramlinks",
    # Diagram Extensions
    "sphinxcontrib-mermaid",
    "sphinxcontrib-plantuml",
    # API Documentation
    "sphinxcontrib-httpdomain",
    "sphinx-click",
    "sphinx-argparse",
    # Additional features
    "sphinx-collapse",
    "sphinx-panels",
    "sphinx-exec-directive",
    "sphinx-prompt",
]

# Full dependencies - everything that might be used
FULL_DEPENDENCIES = EXTENDED_DEPENDENCIES + [
    # Additional UI/UX
    "sphinx-favicon",
    "sphinx-notfound-page",
    "sphinxcontrib-fulltoc",
    "sphinxcontrib-jquery",
    "sphinx-tippy",
    # More diagram support
    "sphinxcontrib-blockdiag",
    "sphinxcontrib-seqdiag",
    "sphinxcontrib-drawio",
    "sphinx-diagrams",
    "sphinx-uml",
    # API/OpenAPI
    "sphinxcontrib-bibtex",
    "sphinxcontrib-openapi",
    "sphinxcontrib-redoc",
    # Media
    "sphinxcontrib-images",
    "sphinxcontrib-youtube",
    "sphinx-carousel",
    "sphinx-charts",
    "sphinx-visualized",
    # SEO/Web
    "sphinx-sitemap",
    "sphinx-reredirects",
    "sphinxext-opengraph",
    "sphinxext-rediraffe",
    "sphinx-last-updated-by-git",
    # Additional features
    "sphinx-contributors",
    "sphinx-git",
    "sphinx-changelog",
    "sphinx-needs",
    "sphinx-examples",
    "sphinx-jsonschema",
    # Export formats
    "sphinx-simplepdf",
    "sphinx-revealjs",
]

# Package mappings
PACKAGES = {
    "core": "haive-core",
    "agents": "haive-agents",
    "tools": "haive-tools",
    "games": "haive-games",
    "mcp": "haive-mcp",
    "dataflow": "haive-dataflow",
    "prebuilt": "haive-prebuilt",
}


@nox.session(python=PYTHON_VERSIONS, name="docs-build-package")
@nox.parametrize("package", list(PACKAGES.keys()))
@nox.parametrize("profile", ["minimal", "standard", "full"])
def docs_build_package(session, package, profile):
    """Build documentation for a specific package with given profile.

    Usage:
        nox -s docs-build-package -- core minimal
        nox -s docs-build-package -- agents standard
        nox -s docs-build-package -- tools full
    """
    # Install dependencies based on profile
    if profile == "minimal":
        session.install(*BASE_DEPENDENCIES)
    elif profile == "standard":
        session.install(*BASE_DEPENDENCIES, *EXTENDED_DEPENDENCIES)
    else:  # full
        session.install(*BASE_DEPENDENCIES, *FULL_DEPENDENCIES)

    session.log(f"📦 Building {package} documentation with {profile} profile")

    build_dir = DOCS_DIR / "build" / f"{package}_{profile}"

    # Create configuration using modular builder
    with tempfile.TemporaryDirectory() as temp_dir:
        temp_path = Path(temp_dir)

        # Copy conf_modules to temp directory
        if CONF_MODULES_DIR.exists():
            shutil.copytree(CONF_MODULES_DIR, temp_path / "conf_modules")

        # Create conf.py using modular builder
        conf_content = f'''
"""
Sphinx configuration for Haive {package.title()} package.
Generated by modular build system with {profile} profile.
"""

import sys
from pathlib import Path

# Add conf_modules to path
sys.path.insert(0, str(Path(__file__).parent / "conf_modules"))

# Import modular builder
from modular_builder import ModularSphinxBuilder

# Create builder and get configuration
builder = ModularSphinxBuilder("{package}", "{profile}")
config = builder.get_sphinx_config()

# Apply configuration
for key, value in config.items():
    globals()[key] = value

# Print summary
builder.print_build_summary()
'''

        conf_file = temp_path / "conf.py"
        conf_file.write_text(conf_content)

        # Create index content
        index_content = f"""
Haive {package.title()} Documentation
{"=" * (len(package) + 21)}

Welcome to the documentation for the **haive-{package}** package.

This documentation was built using the **{profile}** profile.

.. toctree::
   :maxdepth: 2
   :caption: Contents:

   api/index

Package Overview
----------------

The haive-{package} package provides...

Profile Information
-------------------

Built with the following profile:

- **Profile Level**: {profile}
- **Package**: haive-{package}
- **Theme**: Furo

API Reference
-------------

.. autoapi-toctree::
   :maxdepth: 2
"""
        (temp_path / "index.rst").write_text(index_content)

        # Clean build directory
        if build_dir.exists():
            shutil.rmtree(build_dir)
        build_dir.mkdir(parents=True, exist_ok=True)

        # Build documentation
        start_time = time.time()

        try:
            session.run(
                "sphinx-build",
                "-b",
                "html",
                "-c",
                str(temp_path),
                str(temp_path),
                str(build_dir),
                "-W",  # Treat warnings as errors
                "--keep-going",  # Continue on errors
                "-v",  # Verbose
            )

            build_time = time.time() - start_time

            # Check results
            html_files = list(build_dir.glob("**/*.html"))
            session.log(
                f"✅ Build successful: {len(html_files)} files in {build_time:.1f}s",
            )

            # Show result location
            index_file = build_dir / "index.html"
            if index_file.exists():
                session.log(
                    f"📄 View documentation: file://{index_file.absolute()}")

        except Exception as e:
            build_time = time.time() - start_time
            session.log(f"❌ Build failed after {build_time:.1f}s: {e}")
            session.error(f"Build failed for {package} with {profile} profile")


@nox.session(python=PYTHON_VERSIONS, name="docs-test-modular")
def docs_test_modular_system(session):
    """Test the modular configuration system itself."""

    session.install(*BASE_DEPENDENCIES)

    session.log("🧪 Testing modular configuration system")

    # Test that we can import and use the modular system
    test_script = f"""
import sys
from pathlib import Path

# Add conf_modules to path
conf_modules_dir = Path("{CONF_MODULES_DIR}")
sys.path.insert(0, str(conf_modules_dir))

print("Testing modular imports...")

# Test package configs
try:
    from package_configs import PACKAGE_PROFILES, get_package_extensions
    print(f"✅ Package configs loaded: {{len(PACKAGE_PROFILES)}} packages")

    # Test each package
    for package in PACKAGE_PROFILES.keys():
        minimal = get_package_extensions(package, "minimal")
        standard = get_package_extensions(package, "standard")
        full = get_package_extensions(package, "full")
        print(f"  {{package}}: minimal={{len(minimal)}}, standard={{len(standard)}}, full={{len(full)}}")
except Exception as e:
    print(f"❌ Package configs failed: {{e}}")
    raise

# Test modular builder
try:
    from modular_builder import ModularSphinxBuilder

    # Test building config for each package
    for package in ["core", "agents", "tools"]:
        builder = ModularSphinxBuilder(package, "minimal")
        config = builder.get_sphinx_config()
        print(f"✅ Builder test for {{package}}: {{len(config['extensions'])}} extensions")
except Exception as e:
    print(f"❌ Modular builder failed: {{e}}")
    raise

print("\\n🎉 All modular system tests passed!")
"""

    # Run the test
    session.run("python", "-c", test_script)


@nox.session(python=PYTHON_VERSIONS, name="docs-list-profiles")
def docs_list_profiles(session):
    """List all available package profiles and their extensions."""

    # Install rich for nice table display
    session.install("rich")

    session.log("📋 Listing all package profiles")

    list_script = f"""
import sys
from pathlib import Path

# Add conf_modules to path
sys.path.insert(0, str(Path("{CONF_MODULES_DIR}")))

from package_configs import PACKAGE_PROFILES, get_common_extensions
from rich.console import Console
from rich.table import Table

console = Console()

# Create summary table
table = Table(title="Package Extension Profiles", show_header=True)
table.add_column("Package", style="cyan", width=12)
table.add_column("Minimal", justify="right", style="yellow")
table.add_column("Standard", justify="right", style="green")
table.add_column("Full", justify="right", style="blue")

for package_name, profile in PACKAGE_PROFILES.items():
    table.add_row(
        package_name,
        str(len(profile.minimal)),
        str(len(profile.standard)),
        str(len(profile.full))
    )

console.print(table)

# Show common extensions
common = get_common_extensions(4)
console.print(f"\\n[bold]Extensions used by 4+ packages:[/bold] {{len(common)}}")
for ext in sorted(common)[:10]:
    console.print(f"  • {{ext}}")
if len(common) > 10:
    console.print(f"  ... and {{len(common) - 10}} more")
"""

    session.run("python", "-c", list_script)


@nox.session(python=PYTHON_VERSIONS, name="docs-quick")
@nox.parametrize("package", ["core", "agents"])
def docs_quick_build(session, package):
    """Quick documentation build for development (minimal profile).

    This is the fastest way to build docs for a package during
    development.
    """
    session.install(*BASE_DEPENDENCIES)

    session.log(f"⚡ Quick build for {package}")

    # Use minimal profile for speed
    build_dir = DOCS_DIR / "build" / f"{package}_quick"

    with tempfile.TemporaryDirectory() as temp_dir:
        temp_path = Path(temp_dir)

        # Copy conf_modules
        if CONF_MODULES_DIR.exists():
            shutil.copytree(CONF_MODULES_DIR, temp_path / "conf_modules")

        # Minimal conf.py with project root
        conf_file = temp_path / "conf.py"
        conf_file.write_text(
            f"""
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent / "conf_modules"))

from modular_builder import ModularSphinxBuilder

# Pass the actual project root for proper path resolution
project_root = Path("{PROJECT_ROOT}")
builder = ModularSphinxBuilder("{package}", "minimal", project_root=project_root)
config = builder.get_sphinx_config()

for key, value in config.items():
    globals()[key] = value
""", )

        # Minimal index
        index_file = temp_path / "index.rst"
        index_file.write_text(
            f"""
{package.title()} Quick Build
{"=" * (len(package) + 12)}

.. toctree::
   :maxdepth: 2

   api/index
""", )

        # Build
        if build_dir.exists():
            shutil.rmtree(build_dir)

        start_time = time.time()
        try:
            # Run sphinx-build (may have some warnings but that's OK for quick builds)
            result = session.run(
                "sphinx-build",
                "-b",
                "html",
                str(temp_path),
                str(build_dir),
                "-q",  # Quiet mode for quick builds
                success_codes=[
                    0,
                    1,
                    2,
                    # Accept exit codes 0, 1 (warnings), or 2 (errors that still
                    # produced output)
                ],
                silent=True,
            )
            build_time = time.time() - start_time
            session.log(f"✅ Quick build complete in {build_time:.1f}s")

            # Check if index.html was created
            index_file = build_dir / "index.html"
            if index_file.exists():
                session.log(f"📄 View: file://{index_file}")
            else:
                session.log(
                    "⚠️  No index.html found, checking for other HTML files..."
                )
                html_files = list(build_dir.rglob("*.html"))
                if html_files:
                    session.log(f"📄 Found {len(html_files)} HTML files")
                    session.log(
                        f"📄 API docs: file://{build_dir / 'api' / 'index.html'}",
                    )
        except Exception as e:
            session.error(f"❌ Build failed: {e}")
            raise


@nox.session(python=PYTHON_VERSIONS, name="docs-compare-profiles")
@nox.parametrize("package", ["agents"])
def docs_compare_profiles(session, package):
    """Build the same package with all three profiles for comparison."""

    session.install(*BASE_DEPENDENCIES, *FULL_DEPENDENCIES)

    session.log(f"🔬 Building {package} with all profiles for comparison")

    results = {}

    for profile in ["minimal", "standard", "full"]:
        session.log(f"\n📦 Building with {profile} profile...")

        build_dir = DOCS_DIR / "build" / f"compare_{package}_{profile}"

        with tempfile.TemporaryDirectory() as temp_dir:
            temp_path = Path(temp_dir)

            # Copy conf_modules
            if CONF_MODULES_DIR.exists():
                shutil.copytree(CONF_MODULES_DIR, temp_path / "conf_modules")

            # Create conf.py
            conf_file = temp_path / "conf.py"
            conf_file.write_text(
                f"""
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent / "conf_modules"))

from modular_builder import ModularSphinxBuilder

builder = ModularSphinxBuilder("{package}", "{profile}")
config = builder.get_sphinx_config()

for key, value in config.items():
    globals()[key] = value

# Store stats for comparison
with open("build_stats.txt", "w") as f:
    f.write(f"extensions={{len(config.get('extensions', []))}}")
""", )

            # Create index
            index_file = temp_path / "index.rst"
            index_file.write_text(
                f"""
{package.title()} - {profile.title()} Profile
{"=" * (len(package) + len(profile) + 12)}

Built with **{profile}** profile.

.. toctree::
   :maxdepth: 2

   api/index
""", )

            # Build
            if build_dir.exists():
                shutil.rmtree(build_dir)

            start_time = time.time()
            try:
                session.run(
                    "sphinx-build",
                    "-b",
                    "html",
                    str(temp_path),
                    str(build_dir),
                    "-q",
                )
                build_time = time.time() - start_time

                # Count files
                html_files = list(build_dir.glob("**/*.html"))

                # Read extension count
                stats_file = temp_path / "build_stats.txt"
                if stats_file.exists():
                    stats = stats_file.read_text()
                    ext_count = int(stats.split("=")[1])
                else:
                    ext_count = 0

                results[profile] = {
                    "success": True,
                    "time": build_time,
                    "files": len(html_files),
                    "extensions": ext_count,
                    "path": build_dir / "index.html",
                }

            except Exception as e:
                results[profile] = {"success": False, "error": str(e)}

    # Print comparison
    session.log("\n📊 Profile Comparison Results:")
    session.log("-" * 60)
    session.log(
        f"{'Profile':<10} {'Status':<10} {'Time':<10} {'Files':<10} {'Extensions':<10}",
    )
    session.log("-" * 60)

    for profile, result in results.items():
        if result["success"]:
            session.log(
                f"{profile:<10} {'✅':<10} {result['time']:<10.1f} "
                f"{result['files']:<10} {result['extensions']:<10}", )
            session.log(f"  📄 {result['path']}")
        else:
            session.log(f"{profile:<10} {'❌':<10} Failed: {result['error']}")


if __name__ == "__main__":
    print("Modular Documentation Build System")
    print("==================================")
    print()
    print("Available sessions:")
    print("  nox -s docs-build-package         # Build specific package")
    print("  nox -s docs-test-modular          # Test the modular system")
    print("  nox -s docs-list-profiles         # List all profiles")
    print("  nox -s docs-quick                 # Quick minimal build")
    print("  nox -s docs-compare-profiles      # Compare all profiles")
    print()
    print("Examples:")
    print("  nox -s docs-build-package-core-standard")
    print("  nox -s docs-build-package-agents-full")
    print("  nox -s docs-quick-agents")
    print("  nox -s docs-compare-profiles-agents")
